// projectsData.js
const projectsData = [
    {
        title: 'appNba',
        description: '',
        videoSrc: '',
        imageSrc: './assets/projects/nbaApp.png',
        technologies: ['JAVA', 'SPRING', 'ANGULAR', 'HTML', 'CSS'],
        githubLink: 'https://github.com/Alvarosanchezz3/NBA-AppWeb',
    },
    {
        title: 'Client App - JPA',
        description: '',
        videoSrc: '',
        imageSrc: './assets/projects/proyecto-JPA.png',
        technologies: ['JAVA', 'SPRING', 'HTML', 'CSS'],
        githubLink: 'https://github.com/Alvarosanchezz3/SpringBoot-JPA',
    },
    {
      title: 'Nike',
      description: '',
      videoSrc: './assets/projects/nikeCard.mp4',
      imageSrc: '',
      technologies: ['HTML', 'Sass', 'JS'],
      githubLink: 'https://github.com/Alvarosanchezz3/Nike-Card',
    },
    {
      title: 'Calculator',
      description: '',
      videoSrc: './assets/projects/Calculator.mp4',
      technologies: ['HTML', 'CSS', 'JS'],
      githubLink: 'https://github.com/Alvarosanchezz3/Calculator',
    },
    {
        title: 'Animated menu',
        description: '',
        videoSrc: './assets/projects/menu-animado.webm',
        technologies: ['HTML', 'CSS', 'SASS'],
        githubLink: 'https://github.com/Alvarosanchezz3/Animated-menu',
    },
    {
        title: 'Login-register',
        description: '',
        videoSrc: './assets/projects/login.webm',
        technologies: ['HTML', 'SASS', 'JS'],
        githubLink: 'https://github.com/Alvarosanchezz3/Login-Registrer',
    },
    {
        title: 'TWD Netflix Page',
        description: '',
        videoSrc: './assets/projects/TWD-Netflix.mp4',
        technologies: ['HTML', 'SASS', 'JS'],
        githubLink: 'https://github.com/Alvarosanchezz3/NetflixPage',
    },
    {
        title: 'WeatherApp',
        description: '',
        videoSrc: './assets/projects/weatherApp.webm',
        technologies: ['HTML', 'SASS', 'JS'],
        githubLink: 'https://github.com/Alvarosanchezz3/WeatherApp',
    },
    {
        title: 'Pokemon Couples Game',
        description: '',
        videoSrc: './assets/projects/PokemonParejas.mp4',
        technologies: ['JAVA', 'ECLIPSE'],
        githubLink: 'https://github.com/Alvarosanchezz3/Pokemon-CouplesGame',
    },
    {
        title: 'API REST',
        description: '',
        videoSrc: '',
        imageSrc: './assets/projects/API REST.jpg',
        technologies: ['JAVA', 'SPRING', 'DOCKER'],
        githubLink: 'https://github.com/Alvarosanchezz3/SpringBootAPI',
    },
    {
        title: 'Spring Forms',
        description: '',
        videoSrc: '',
        imageSrc: './assets/projects/Forms.png',
        technologies: ['JAVA', 'SPRING'],
        githubLink: 'https://github.com/Alvarosanchezz3/SpringBoot-Form',
    },
    {
        title: 'Spring Interceptors',
        description: '',
        videoSrc: '',
        imageSrc: './assets/projects/Interceptores.png',
        technologies: ['JAVA', 'SPRING', 'HTML', 'CSS'],
        githubLink: 'https://github.com/Alvarosanchezz3/SpringBoot-Horario',
    },
    {
        title: 'Error handling in Spring',
        description: '',
        videoSrc: '',
        imageSrc: './assets/projects/errores.png',
        technologies: ['JAVA', 'SPRING', 'HTML', 'CSS'],
        githubLink: 'https://github.com/Alvarosanchezz3/SpringBoot-Errors',
    },
    // Agrega más objetos para representar más proyectos según sea necesario
  ];
  
export default projectsData;